



mode: train  # mode, i.e. train, val, predict,
save_dir:  # path to save directory
dataset_path: 
debug: True # (bool) enable debug mode

# Train settings -------------------------------------------------------------------------------------------------------
project:  # project name
name: default
model:  # path to model file, i.e. yolov8n.pt, yolov8n.yaml
resume:  False # resume training from checkpoint
epochs: 100  # number of epochs to train for
patience: 50  # epochs to wait for no observable improvement for early stopping of training
batch: 48  # number of images per batch (-1 for AutoBatch)
imgsz: 640  # size of input images as integer or w,h
inp_size: 224
device: 0,1,2 # device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
save: False # save train checkpoints and predict results
save_period: -1 # Save checkpoint every x epochs (disabled if < 1)
optimizer: AdamW  # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True  # (bool) whether to print verbose output
cos_lr: False  # (bool) use cosine learning rate scheduler
workers: 16  # (int) number of worker threads for data loading (per RANK if DDP)
plots: True  # (bool) plot training results

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: False # (bool) validate/test during training
split: val  # (str) dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # (bool) save results to JSON file
save_hybrid: False  # (bool) save hybrid version of labels (labels + additional predictions)
conf:  # (float, optional) object confidence threshold for detection (default 0.25 predict, 0.001 val)
half: False  # (bool) use half precision (FP16)
dnn: False  # (bool) use OpenCV DNN for ONNX inference

# Prediction settings --------------------------------------------------------------------------------------------------
source:  # (str, optional) source directory for images or videos
show: False  # (bool) show results if possible
save_txt: False  # (bool) save results as .txt file


# Data setting 
names: ["first", "second"]


# Model settings

backbone:
  freeze: False #False #True
  type: maxxvitv2_rmlp_base_rw_224.sw_in12k
  init_cfg:
        pretrained: True 
        in_chans: 3
        features_only: True
        out_indices: [4, ]  

in_channels: 3
out_channels: 3
channels: 16
n_res_blocks: 3
attention_levels: [0,1, 2,3]
attention_mode: "gat"
channel_multipliers: [1, 2, 2, 4, 4, 8]
unpooling_levels: [0, 1, 2]
n_heads: 4
d_cond: 768 #1024



# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.001  # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.001  # (float) final learning rate (lr0 * lrf)
momentum: 0.937  # (float) SGD momentum/Adam beta1
weight_decay: 0.0005  # (float) optimizer weight decay 5e-4
warmup_epochs: 0 #3.0  # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8  # (float) warmup initial momentum
warmup_bias_lr: 0.001 # (float) warmup initial bias lr
nbs: 64  # (int) nominal batch size
#augs